# Generated by Django 4.0.4 on 2022-05-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_ratingstar_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(max_length=100, null=True, verbose_name='Слоган'),
        ),
    ]
